version: '1.0.0'
services:
  jss_reader-go:
    image: jss_reader-go:1.1.0
    restart: always
    depends_on:
      - mysql
      - redis
    ports:
      - "8000:8000"
  jss_reader-react:
    image: jss_reader-react:1.1.0
    restart: always
    ports:
      - "80:3000"
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    # set character set and collation
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - ./mysql-data:/var/lib/mysql
  redis:
    image: redis:6.2.6
    restart: always
    ports:
      - "6379:6379"
    command: "redis-server /etc/redis/redis.conf --appendonly yes --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}"
    volumes:
      - ./redis-data:/data
      - ./redis.conf:/etc/redis/redis.conf