INSERT INTO `explores` (`url`, `name`, `category`) VALUES ('https://rsshub.app/sjtu/seiee/academic', '电子信息与电气工程学院学术动态', 'SJTU');
INSERT INTO `explores` (`url`, `name`, `category`) VALUES ('https://rsshub.app/sjtu/seiee/xsb/news', '电子信息与电气工程学院学生工作办公室', 'SJTU');
INSERT INTO `explores` (`url`, `name`, `category`) VALUES ('https://rsshub.app/sjtu/gs/enroll/59', '研究生通知公告', 'SJTU');
INSERT INTO `explores` (`url`, `name`, `category`) VALUES ('https://rsshub.app/sjtu/jwc', '教务处通知公告', 'SJTU');
INSERT INTO `explores` (`url`, `name`, `category`) VALUES ('https://rsshub.app/sjtu/yzb/zkxx/sszs', '研究生招生网招考信息', 'SJTU');
INSERT INTO `explores` (`url`, `name`, `category`) VALUES ('https://rsshub.app/usenix/usenix-security-sympoium', 'USENIX Security', 'Journal');
INSERT INTO `explores` (`url`, `name`, `category`) VALUES ('https://rsshub.app/ieee-security/security-privacy', 'IEEE Symposium on Security and Privacy', 'Journal');
INSERT INTO `explores` (`url`, `name`, `category`) VALUES ('https://rsshub.app/ndss-symposium/ndss', 'Network and Distributed System Security (NDSS) Symposium', 'Journal');
INSERT INTO `explores` (`url`, `name`, `category`) VALUES ('https://rsshub.app/nature/research/ng', 'Nature (Nature Genetics) | Latest Research', 'Journal');
INSERT INTO `explores` (`url`, `name`, `category`) VALUES ('https://feeds.science.org/rss/science.xml', 'Science', 'Journal');
INSERT INTO `explores` (`url`, `name`, `category`) VALUES ('https://rsshub.app/mihoyo/ys/main/latest', '原神最新资讯', 'Gaming');
INSERT INTO `explores` (`url`, `name`, `category`) VALUES ('https://rsshub.app/mihoyo/sr/zh-cn', '崩坏：星穹铁道最新资讯', 'Gaming');
INSERT INTO `explores` (`url`, `name`, `category`) VALUES ('https://rsshub.app/arknights/news', '明日方舟游戏公告与新闻', 'Gaming');
INSERT INTO `explores` (`url`, `name`, `category`) VALUES ('https://rsshub.app/tencent/pvp/newsindex/all', '王者荣耀新闻中心', 'Gaming');
INSERT INTO `explores` (`url`, `name`, `category`) VALUES ('https://rsshub.app/lol/newsindex/all', '英雄联盟国服新闻', 'Gaming');
INSERT INTO `explores` (`url`, `name`, `category`) VALUES ('https://rsshub.app/yxdzqb/low', 'steam史低', 'Gaming');
INSERT INTO `explores` (`url`, `name`, `category`) VALUES ('https://rsshub.app/bilibili/popular/all', 'b站综合热门', 'Entertainment');
INSERT INTO `explores` (`url`, `name`, `category`) VALUES ('https://rsshub.app/bilibili/ranking/0/3/1', 'b站排行榜', 'Entertainment');
INSERT INTO `explores` (`url`, `name`, `category`) VALUES ('https://rsshub.app/bilibili/weekly', 'b站每周必看', 'Entertainment');
INSERT INTO `explores` (`url`, `name`, `category`) VALUES ('https://rsshub.app/pixiv/ranking/week', 'pixiv周排行', 'Entertainment');
INSERT INTO `explores` (`url`, `name`, `category`) VALUES ('https://rsshub.app/douban/movie/playing', '豆瓣：正在上映的电影', 'Entertainment');
INSERT INTO `explores` (`url`, `name`, `category`) VALUES ('https://rsshub.app/douban/movie/weekly', '豆瓣：一周口碑榜', 'Entertainment');
INSERT INTO `explores` (`url`, `name`, `category`) VALUES ('https://rsshub.app/douban/book/latest', '豆瓣：新书速递', 'Entertainment');
INSERT INTO `explores` (`url`, `name`, `category`) VALUES ('https://rsshub.app/douban/book/rank/fiction', '豆瓣：热门图书排行', 'Entertainment');
INSERT INTO `explores` (`url`, `name`, `category`) VALUES ('https://rsshub.app/zhihu/hotlist', '知乎热榜', 'Information');
INSERT INTO `explores` (`url`, `name`, `category`) VALUES ('https://rss.mifaw.com/articles/5c8bb11a3c41f61efd36683e/5c919dc93882afa09dff3fc7', '知乎日报', 'Information');
INSERT INTO `explores` (`url`, `name`, `category`) VALUES ('https://rsshub.app/weibo/search/hot', '微博热搜榜', 'Information');
INSERT INTO `explores` (`url`, `name`, `category`) VALUES ('https://rsshub.app/thepaper/featured', '澎湃新闻：首页头条', 'Information');
INSERT INTO `explores` (`url`, `name`, `category`) VALUES ('https://rsshub.app/ielts', '雅思最新消息', 'Information');
INSERT INTO `explores` (`url`, `name`, `category`) VALUES ('https://rsshub.app/baidu/tieba/forum/good/孙笑川', '孙吧精品贴', 'Information');
INSERT INTO `explores` (`url`, `name`, `category`) VALUES ('https://rsshub.app/ctfhub/search', '查询国内外 CTF 赛事信息', 'Information');
