INSERT INTO `explores` (`url`, `name`, `category`) VALUES ('https://rsshub.app/sjtu/seiee/academic', '电子信息与电气工程学院学术动态', 'sjtu');
INSERT INTO `explores` (`url`, `name`, `category`) VALUES ('https://rsshub.app/sjtu/seiee/bjwb/major_select', '电子信息与电气工程学院本科教务办', 'sjtu');
INSERT INTO `explores` (`url`, `name`, `category`) VALUES ('https://rsshub.app/sjtu/seiee/xsb/news', '电子信息与电气工程学院学生工作办公室', 'sjtu');
INSERT INTO `explores` (`url`, `name`, `category`) VALUES ('https://rsshub.app/sjtu/gs/enroll/59', '研究生通知公告', 'sjtu');
INSERT INTO `explores` (`url`, `name`, `category`) VALUES ('https://rsshub.app/ctfhub/search', '查询国内外 CTF 赛事信息', 'sjtu');
INSERT INTO `explores` (`url`, `name`, `category`) VALUES ('https://rsshub.app/sjtu/jwc', '教务处通知公告', 'sjtu');
INSERT INTO `explores` (`url`, `name`, `category`) VALUES ('https://rsshub.app/sjtu/yzb/zkxx/sszs', '研究生招生网招考信息', 'sjtu');
INSERT INTO `explores` (`url`, `name`, `category`) VALUES ('https://shuiyuan.sjtu.edu.cn/posts.rss', '水源社区最新帖子', 'sjtu');
INSERT INTO `explores` (`url`, `name`, `category`) VALUES ('https://shuiyuan.sjtu.edu.cn/latest.rss', '水源社区最新话题', 'sjtu');
INSERT INTO `explores` (`url`, `name`, `category`) VALUES ('https://rsshub.app/usenix/usenix-security-sympoium', 'USENIX Security', '期刊');
INSERT INTO `explores` (`url`, `name`, `category`) VALUES ('https://rsshub.app/ieee-security/security-privacy', 'IEEE Symposium on Security and Privacy', '期刊');
INSERT INTO `explores` (`url`, `name`, `category`) VALUES ('https://rsshub.app/ndss-symposium/ndss', 'Network and Distributed System Security (NDSS) Symposium', '期刊');
INSERT INTO `explores` (`url`, `name`, `category`) VALUES ('rsshub.app/mihoyo/ys/main/latest', '原神最新资讯', '游戏');
INSERT INTO `explores` (`url`, `name`, `category`) VALUES ('rsshub.app/mihoyo/sr/zh-cn', '崩坏：星穹铁道最新资讯', '游戏');
INSERT INTO `explores` (`url`, `name`, `category`) VALUES ('https://rsshub.app/arknights/news', '明日方舟游戏公告与新闻', '游戏');
INSERT INTO `explores` (`url`, `name`, `category`) VALUES ('https://rsshub.app/tencent/pvp/newsindex/all', '王者荣耀新闻中心', '游戏');
INSERT INTO `explores` (`url`, `name`, `category`) VALUES ('https://rsshub.app/lol/newsindex/all', '英雄联盟国服新闻', '游戏');
INSERT INTO `explores` (`url`, `name`, `category`) VALUES ('rsshub.app/yxdzqb/low', 'steam史低', '游戏');
INSERT INTO `explores` (`url`, `name`, `category`) VALUES ('https://rsshub.app/bilibili/popular/all', 'b站综合热门', '娱乐');
INSERT INTO `explores` (`url`, `name`, `category`) VALUES ('https://rsshub.app/bilibili/ranking/0/3/1', 'b站排行榜', '娱乐');
INSERT INTO `explores` (`url`, `name`, `category`) VALUES ('https://rsshub.app/bilibili/weekly', 'b站每周必看', '娱乐');
INSERT INTO `explores` (`url`, `name`, `category`) VALUES ('https://rsshub.app/pixiv/ranking/week', 'pixiv周排行', '娱乐');
INSERT INTO `explores` (`url`, `name`, `category`) VALUES ('https://rsshub.app/douban/movie/playing', '豆瓣：正在上映的电影', '娱乐');
INSERT INTO `explores` (`url`, `name`, `category`) VALUES ('https://rsshub.app/douban/movie/weekly', '豆瓣：一周口碑榜', '娱乐');
INSERT INTO `explores` (`url`, `name`, `category`) VALUES ('https://rsshub.app/douban/book/latest', '豆瓣：新书速递', '娱乐');
INSERT INTO `explores` (`url`, `name`, `category`) VALUES ('https://rsshub.app/douban/book/rank/fiction', '豆瓣：热门图书排行', '娱乐');
INSERT INTO `explores` (`url`, `name`, `category`) VALUES ('https://rsshub.app/zhihu/hotlist', '知乎热榜', '资讯');
INSERT INTO `explores` (`url`, `name`, `category`) VALUES ('https://rss.mifaw.com/articles/5c8bb11a3c41f61efd36683e/5c919dc93882afa09dff3fc7', '知乎日报', '资讯');
INSERT INTO `explores` (`url`, `name`, `category`) VALUES ('https://rsshub.app/weibo/search/hot', '微博热搜榜', '资讯');
INSERT INTO `explores` (`url`, `name`, `category`) VALUES ('https://rsshub.app/thepaper/featured', '澎湃新闻：首页头条', '资讯');
INSERT INTO `explores` (`url`, `name`, `category`) VALUES ('https://rsshub.app/ielts', '雅思最新消息', '资讯');
INSERT INTO `explores` (`url`, `name`, `category`) VALUES ('rsshub.app/baidu/tieba/forum/good/孙笑川', '孙吧精品贴', '资讯');
