INSERT INTO `explores` (`name`, `url`, `image`, `category`) VALUES ('电子信息与电气工程学院学术动态', 'https://rsshub.rssforever.com/sjtu/seiee/academic', '/path/to/sjtu.png', 'SJTU');
INSERT INTO `explores` (`name`, `url`, `image`, `category`) VALUES ('电子信息与电气工程学院学生工作办公室', 'https://rsshub.rssforever.com/sjtu/seiee/xsb/news', '/path/to/sjtu.png', 'SJTU');
INSERT INTO `explores` (`name`, `url`, `image`, `category`) VALUES ('研究生通知公告', 'https://rsshub.rssforever.com/sjtu/gs/enroll/59', '/path/to/sjtu.png', 'SJTU');
INSERT INTO `explores` (`name`, `url`, `image`, `category`) VALUES ('教务处通知公告', 'https://rsshub.rssforever.com/sjtu/jwc', '/path/to/sjtu.png', 'SJTU');
INSERT INTO `explores` (`name`, `url`, `image`, `category`) VALUES ('研究生招生网招考信息', 'https://rsshub.rssforever.com/sjtu/yzb/zkxx/sszs', '/path/to/sjtu.png', 'SJTU');
INSERT INTO `explores` (`name`, `url`, `image`, `category`) VALUES ('USENIX Security', 'https://rsshub.rssforever.com/usenix/usenix-security-sympoium', '/path/to/usenix.png', 'Journal');
INSERT INTO `explores` (`name`, `url`, `image`, `category`) VALUES ('IEEE Symposium on Security and Privacy', 'https://rsshub.rssforever.com/ieee-security/security-privacy', '/path/to/ieee.png', 'Journal');
INSERT INTO `explores` (`name`, `url`, `image`, `category`) VALUES ('Network and Distributed System Security (NDSS) Symposium', 'https://rsshub.rssforever.com/ndss-symposium/ndss', '/path/to/ndss.png', 'Journal');
INSERT INTO `explores` (`name`, `url`, `image`, `category`) VALUES ('Nature (Nature Genetics) | Latest Research', 'https://rsshub.rssforever.com/nature/research/ng', '/path/to/nature.png', 'Journal');
INSERT INTO `explores` (`name`, `url`, `image`, `category`) VALUES ('Science', 'https://feeds.science.org/rss/science.xml', '/path/to/science.png', 'Journal');
INSERT INTO `explores` (`name`, `url`, `image`, `category`) VALUES ('原神最新资讯', 'https://rsshub.rssforever.com/mihoyo/ys/main/latest', '/path/to/genshin.png', 'Gaming');
INSERT INTO `explores` (`name`, `url`, `image`, `category`) VALUES ('崩坏：星穹铁道最新资讯', 'https://rsshub.rssforever.com/mihoyo/sr/zh-cn', '/path/to/starrail.png', 'Gaming');
INSERT INTO `explores` (`name`, `url`, `image`, `category`) VALUES ('明日方舟游戏公告与新闻', 'https://rsshub.rssforever.com/arknights/news', '/path/to/arknights.png', 'Gaming');
INSERT INTO `explores` (`name`, `url`, `image`, `category`) VALUES ('王者荣耀新闻中心', 'https://rsshub.rssforever.com/tencent/pvp/newsindex/all', '/path/to/hok.png', 'Gaming');
INSERT INTO `explores` (`name`, `url`, `image`, `category`) VALUES ('英雄联盟国服新闻', 'https://rsshub.rssforever.com/lol/newsindex/all', '/path/to/lol.png', 'Gaming');
INSERT INTO `explores` (`name`, `url`, `image`, `category`) VALUES ('steam史低', 'https://rsshub.rssforever.com/yxdzqb/low', '/path/to/steam.png', 'Gaming');
INSERT INTO `explores` (`name`, `url`, `image`, `category`) VALUES ('b站综合热门', 'https://rsshub.rssforever.com/bilibili/popular/all', '/path/to/bilibili.png', 'Entertainment');
INSERT INTO `explores` (`name`, `url`, `image`, `category`) VALUES ('b站排行榜', 'https://rsshub.rssforever.com/bilibili/ranking/0/3/1', '/path/to/bilibili.png', 'Entertainment');
INSERT INTO `explores` (`name`, `url`, `image`, `category`) VALUES ('b站每周必看', 'https://rsshub.rssforever.com/bilibili/weekly', '/path/to/bilibili.png', 'Entertainment');
INSERT INTO `explores` (`name`, `url`, `image`, `category`) VALUES ('pixiv周排行', 'https://rsshub.rssforever.com/pixiv/ranking/week', '/path/to/pixiv.png', 'Entertainment');
INSERT INTO `explores` (`name`, `url`, `image`, `category`) VALUES ('豆瓣：一周口碑榜', 'https://rsshub.rssforever.com/douban/movie/weekly', '/path/to/douban.png', 'Entertainment');
INSERT INTO `explores` (`name`, `url`, `image`, `category`) VALUES ('豆瓣：新书速递', 'https://rsshub.rssforever.com/douban/book/latest', '/path/to/douban.png', 'Entertainment');
INSERT INTO `explores` (`name`, `url`, `image`, `category`) VALUES ('豆瓣：热门图书排行', 'https://rsshub.rssforever.com/douban/book/rank/fiction', '/path/to/douban.png', 'Entertainment');
INSERT INTO `explores` (`name`, `url`, `image`, `category`) VALUES ('知乎热榜', 'https://rsshub.rssforever.com/zhihu/hotlist', '/path/to/zhihu.png', 'Information');
INSERT INTO `explores` (`name`, `url`, `image`, `category`) VALUES ('知乎日报', 'https://rss.mifaw.com/articles/5c8bb11a3c41f61efd36683e/5c919dc93882afa09dff3fc7', '/path/to/zhihu.png', 'Information');
INSERT INTO `explores` (`name`, `url`, `image`, `category`) VALUES ('微博热搜榜', 'https://rsshub.rssforever.com/weibo/search/hot', '/path/to/xinlangwb.png', 'Information');
INSERT INTO `explores` (`name`, `url`, `image`, `category`) VALUES ('澎湃新闻：首页头条', 'https://rsshub.rssforever.com/thepaper/featured', '/path/to/ppxinwen.png', 'Information');
INSERT INTO `explores` (`name`, `url`, `image`, `category`) VALUES ('雅思最新消息', 'https://rsshub.rssforever.com/ielts', '/path/to/ielts.png', 'Information');
INSERT INTO `explores` (`name`, `url`, `image`, `category`) VALUES ('孙吧精品贴', 'https://rsshub.rssforever.com/baidu/tieba/forum/good/%E5%AD%99%E7%AC%91%E5%B7%9D', '/path/to/sunxiaochuan.png', 'Information');
INSERT INTO `explores` (`name`, `url`, `image`, `category`) VALUES ('查询国内外 CTF 赛事信息', 'https://rsshub.rssforever.com/ctfhub/search', '/path/to/ctf.png', 'Information');
